apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-master
  namespace: default
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearch-master
        image: pires/elasticsearch:master
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
